import { type CookieOptions, cookieStorage } from "./cookies.ts";
import {
  addClearMethod,
  addWithOptionsMethod,
  multiplexStorage,
  makeObjectStorage,
} from "./tools.ts";
import {
  type SyncStorage,
  type SyncStorageWithOptions,
  type AsyncStorage,
  type AsyncStorageWithOptions,
  type PersistenceOptions,
  type PersistenceSyncAPI,
  type PersistenceSyncData,
  type PersistenceSyncCallback,
  makePersisted,
  multiplexSync,
  storageSync,
  messageSync,
  wsSync,
} from "./persisted.ts";
export {
  type CookieOptions,
  cookieStorage,
  addClearMethod,
  addWithOptionsMethod,
  multiplexStorage,
  makeObjectStorage,
  type SyncStorage,
  type SyncStorageWithOptions,
  type AsyncStorage,
  type AsyncStorageWithOptions,
  type PersistenceOptions,
  type PersistenceSyncCallback,
  type PersistenceSyncData,
  type PersistenceSyncAPI,
  makePersisted,
  multiplexSync,
  storageSync,
  wsSync,
  messageSync,
};
