packages:
  - packages/*
  - site

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  sharp: false

minimumReleaseAgeExclude:
  - '@solidjs/signals@2.0.0-beta.18'
  - '@solidjs/web@2.0.0-beta.18'
  - solid-js@2.0.0-beta.18
  - '@dom-expressions/babel-plugin-jsx@0.50.0-next.21'
  - babel-preset-solid@2.0.0-beta.18

onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild

catalog:
  tsdown: ^0.22.3
  unplugin-solid: ^1.0.0
  solid-js: 2.0.0-beta.18
  '@solidjs/web': 2.0.0-beta.18
  '@solidjs/signals': 2.0.0-beta.18
  babel-preset-solid: 2.0.0-beta.18
  '@babel/core': ^7.29.7

catalogs:
  peer:
    solid-js: ^2.0.0-beta.18
    '@solidjs/web': ^2.0.0-beta.18
