packages:
  - packages/*
  - site

overrides:
  react: 19.2.7
  react-dom: 19.2.7

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  sharp: false

onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
