/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlaygroundNameRouteImport } from './routes/playground/$name'
import { Route as PackageNameIndexRouteImport } from './routes/package/$name/index'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundNameRoute = PlaygroundNameRouteImport.update({
  id: '/playground/$name',
  path: '/playground/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const PackageNameIndexRoute = PackageNameIndexRouteImport.update({
  id: '/package/$name/',
  path: '/package/$name/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/test': typeof TestRoute
  '/playground/$name': typeof PlaygroundNameRoute
  '/package/$name/': typeof PackageNameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/test': typeof TestRoute
  '/playground/$name': typeof PlaygroundNameRoute
  '/package/$name': typeof PackageNameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/test': typeof TestRoute
  '/playground/$name': typeof PlaygroundNameRoute
  '/package/$name/': typeof PackageNameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$' | '/test' | '/playground/$name' | '/package/$name/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$' | '/test' | '/playground/$name' | '/package/$name'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/test'
    | '/playground/$name'
    | '/package/$name/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  TestRoute: typeof TestRoute
  PlaygroundNameRoute: typeof PlaygroundNameRoute
  PackageNameIndexRoute: typeof PackageNameIndexRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground/$name': {
      id: '/playground/$name'
      path: '/playground/$name'
      fullPath: '/playground/$name'
      preLoaderRoute: typeof PlaygroundNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/package/$name/': {
      id: '/package/$name/'
      path: '/package/$name'
      fullPath: '/package/$name/'
      preLoaderRoute: typeof PackageNameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  TestRoute: TestRoute,
  PlaygroundNameRoute: PlaygroundNameRoute,
  PackageNameIndexRoute: PackageNameIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
