// SSR fixtures must be generated by the server compiler before the browser
// compiler hydrates them. Never consume stale fixtures after a failed render.
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("../", import.meta.url));
for (const extra of [["--mode", "ssr"], []]) {
  const result = spawnSync(
    process.execPath,
    ["../../node_modules/vitest/vitest.mjs", "run", "--config", "vitest.config.ts", ...extra],
    { cwd: root, stdio: "inherit" },
  );
  if (result.error) throw result.error;
  if (result.status !== 0) process.exit(result.status ?? 1);
}

// GC must run with shipped-build defines, without test-only owner registries.
const gc = spawnSync(process.execPath, ["scripts/test-gc.mjs"], {
  cwd: root,
  stdio: "inherit",
});
if (gc.error) throw gc.error;
if (gc.status !== 0) process.exit(gc.status ?? 1);
